hash-format = "sha256"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "e1dc1bb8a3537b9c5b41cbc6fa97f19729d6c9ab602810da0b192c5fc84eba7e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f34fa12fe7701cf0776fef1a1f1e2e3c7227f53302b3d87b7ff307f0446a68d2"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "f80771c373ac5f054b7c7e198c680cd7fff0fcc40d5753517b4b0acefa1c5729"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "fa3ae5544ef1069c507cdf030c4b8aeceaeea16d39254c373c410c4048c85b45"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "eea37b6a60c019badb137a3e682461cab98ff7cb2e676620cb9fd649d21971d4"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "67e8124a80cfa3257826ca55bcf02e78a803c0fa91ddea815418d7255ef882a3"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "c21e5c7c86e20d26b9936224db71c94558049000dbf2481f3f1649a62b41f2a1"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "a9279c2f2dd4fa46d1946ed3f9b4bff975d635c7849b5abe8efb4186aed67512"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "22a83a04b4df87ab4bbea18228c3cc695551610c66cc79ccc315d783d3f7848f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6563af8f8937ede110303ee1437499892061d824182139a92e7a1fd6eac168d7"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/universal-shops.pw.toml"
hash = "74754469b268378d9c2a672f7fc364da2d3974a9006aff8da7f91f25bc7969d4"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "5df1792af4ba49d779050fe3d2e70bfa04deaade2b891f354e6efcc30baee8cb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true
