name = "FabricMods"
author = "LPbigFish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8f6eaf39e79a9194b98f649bd7d30163d06270269243ec37d8e73a5b0d36edf"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
